game:
  max-players: 10
  min-players: 2

kits:
  Default:
    displayname: "§cBarbarian"
    icon: "DIAMOND_SWORD"
    items:
      - "DIAMOND_SWORD,1,0"
    armor:
      helmet: "DIAMOND_HELMET"
      chestplate: "DIAMOND_CHESTPLATE"
      leggings: "DIAMOND_LEGGINGS"
      boots: "DIAMOND_BOOTS"

    # The time is in seconds and the amplifier is the level of the potion effect
    # Example : "SPEED,10,2" will give the player speed 2 for 10 seconds
    # Set time to -1 to make it permanent
    effects: []


  Archer:
    displayname: "§eArcher"
    icon: "BOW"
    items:
      - "BOW,1,1"
      - "ARROW,64,2"
      - "STONE_SWORD,1,0"
    armor:
      helmet: "LEATHER_HELMET"
      chestplate: "IRON_CHESTPLATE"
      leggings: "LEATHER_LEGGINGS"
      boots: "IRON_BOOTS"
    effects:
      - "SPEED,-1,1"

  Ninja:
    displayname: "§8Ninja"
    icon: "ARROW"
    items:
      - "IRON_SWORD,1,0"
    armor:
      helmet: "LEATHER_HELMET"
      chestplate: "IRON_CHESTPLATE"
      leggings: "LEATHER_LEGGINGS"
      boots: "GOLDEN_BOOTS"
    effects:
      - "SPEED,-1,3"
      - "INVISIBILITY,45,1"

arena:
  name: "Arena"
  world: "world"
  spawn: "-707.5,4,-618,0.0,0.0"
  lobby: "-707.5,10,-653.5,0.0,0.0"
  region:
      min: "-824,0,-520"
      max: "-593,64,-716"
  respawns:
    - "-707.5,4,-641.5,0.0,0.0"
    - "-745.5,4,-618.0,-90.0,0.0"
    - "-707.5,4,-595.5,180.0,0.0"
    - "-667.5,4,-618.0,90.0,0.0"
    - "-707.5,4,-618.0,0.0,0.0"
    - "-679.5,4,-635.5,45.0,0.0"
    - "-735.5,4,-635.5,-45.0,0.0"
    - "-735.5,4,-601.5,-135.0,0.0"
    - "-679.5,4,-601.5,135.0,0.0"