kits:
  Barbarian:
    displayname: "§cBarbarian"
    icon: "DIAMOND_SWORD"
    items:
      - "DIAMOND_SWORD,1,0"
    armor:
      helmet: "DIAMOND_HELMET"
      chestplate: "DIAMOND_CHESTPLATE"
      leggings: "DIAMOND_LEGGINGS"
      boots: "DIAMOND_BOOTS"

  Archer:
    displayname: "§eArcher"
    icon: "BOW"
    items:
      - "BOW,1,1"
      - "ARROW,64,2"
      - "STONE_SWORD,1,0"
    armor:
      helmet: "LEATHER_HELMET"
      chestplate: "IRON_CHESTPLATE"
      leggings: "LEATHER_LEGGINGS"
      boots: "IRON_BOOTS"

arena:
  name: "Arena"
  world: "world"
  spawn: "-618,4,-708,0.0,0.0"
  lobby: "-707.5,10,-653.5,0.0,0.0"
  region:
      min: "-824,0,-520"
      max: "-593,64,-716"