kits:
  Barbarian:
    name: "Barbarian"
    icon: "DIAMOND_SWORD"
    items:
      - "DIAMOND_SWORD,1,0"
    armor:
      helmet: "DIAMOND_HELMET"
      chestplate: "DIAMOND_CHESTPLATE"
      leggings: "DIAMOND_LEGGINGS"
      boots: "DIAMOND_BOOTS"